version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfileweb
    container_name: "web"
    ports:
      - 80:80
    volumes:
      - .web/:/usr/src/app/

  db:
    build:
      context: .
      dockerfile: Dockerfiledb
    container_name: "db"
    ports:
      - 5432:5432
    #volumes:
    #  -
  words:
      build:
        context: .
        dockerfile: Dockerfilewords
      container_name: "words"
      ports:
        - 8080:8080
      volumes:
        - ./words:/usr/src/words
